### ISSUE TITLE
default export for typescript

### ISSUE THREAD

**Issue by saviski** [CGamesPlay/node-callable-instance#4]
https://github.com/CGamesPlay/node-callable-instance/blob/7b88b5ac64bb9fa20690c222185a1928f6b4cab0/index.d.ts#L1

should be 
```
declare const CallableInstance: ICallableInstance;
export default CallableInstance;
```

then you can do `import CallableInstance from 'callable-instance';`

**Comment by saviski** [comment]
Using typescript, I was only able to get it working after this changes:

```typescript
export default class CallableInstance<P> extends Function {
  constructor(property: keyof P);
}

export default interface CallableInstance<P> {
  <T>(...argv: any[]): T;
}
```

then I can do the following on my code:
```typescript
class MyClass extends CallableInstance<MyClass> {
  constructor() {
    super('method');
  }

  method() {

  }
}

let test =  new MyClass ();
test();
```

**Comment by CGamesPlay** [comment]
Hello, thanks for the issue! Can you submit this as a pull request? I'd be happy to merge it :)

**Comment by CL-Jeremy** [comment]
I have no idea why, but absolutely none of the above works for me as of today.
Both versions suggested here would not compile at all using TypeScript 3.9.6. The repo version doesn't give any error at compile time, but outputs a faulty JavaScript, which is supposedly the reason for this issue in the first place.
The only solution for now, after hours of trial and error, was to downgrade to version 1.0.0 of this package and actually use it as JavaScript:
```ts
import * as CallableInstance from 'callable-instance';
```

**Comment by CGamesPlay** [comment]
OK, I am investigating this now. What I do know (after researching) is that the correct way to import the module in TypeScript is actually like this:

```typescript
import CallableInstance = require('callable-instance');
```

I will figure out how to make TypeScript cooperate and will push an update.

**Comment by CL-Jeremy** [comment]
> OK, I am investigating this now. What I do know (after researching) is that the correct way to import the module in TypeScript is actually like this:
> 
> ```ts
> import CallableInstance = require('callable-instance');
> ```
> 
> I will figure out how to make TypeScript cooperate and will push an update.

Thanks. Just to say: the syntax I posted above should always compile to
```js
const CallableInstance = require('callable-instance');
```
in JavaScript, so either way that's taking advantage of JavaScript, not TypeScript.

With the TypeScript version, it is failing with this message:

> Error TS2507: Type 'typeof import("[...]/callable-instance/index")' is not a constructor function type

So the valid approach _per se_ would be to follow the steps in README, but that would result in importing from an additional `.default` namespace, at least in the current version of TypeScript.

If there were a way to do something like `export default declare const` this could have worked, but that'll be a pretty nonsensical syntax I think.

**Comment by CGamesPlay** [comment]
It turns out there is such a syntax! `export =`.

In order to get my test cases to work successfully, I needed to change the type parameters around, so I made them accept an argument tuple of types and a return type. This still has some issues, but is pretty usable.

- [x] The resulting instance is callable.
- [x] The types at the call site must match the declared types.
- [ ] The target method must match the declared types.

This last one is annoying, I don't believe it's possible with TypeScript today. I verified these using TypeScript 3.7.5.

I've just published a new version to npm, 2.0.0, which includes these changes. Please give it a try and let me know if it works for you!

**Comment by CL-Jeremy** [comment]
Now that looks quite much like the Java syntax I'm familiar with 😄.

My VS Code keeps on telling me to convert `import * as X from [...]` to `import X from [...]` ("standard import"). Wrong! But I could understand the challenge for a linter to adapt to such manifold syntax variations.

So it seems to work as long as the JavaScript version works, and the TypeScript `.d.ts` ends up allowing the invoking file to resolve to the good ol' JavaScript syntax (as stated above), the goal is reached. So the version below works just as well:
```ts
interface ICallableInstance {
	new <T>(property: string | symbol): (...argv) => T;
	<T>(...argv: any[]): T;
}
declare const CallableInstance: ICallableInstance;
export = CallableInstance;
```
Though, having programmed more in Java than JavaScript/TS/C# altogether, I can well see the potential of TypeScript. We really live in an era full of choices.

**Comment by CGamesPlay** [comment]
Strange that the VS code linter can't handle it. Is it possible that restarting the program fixes that issue? I know my linter doesn't always pick up changes in dependent packages.

The reason for the change is that the resulting function, with the version you've provided, is `(...args: any[]) => T`, whereas the version that I've now published is `(...args: A) => R`. That is to say, arguments are type checked. If you want to use version 2.0.0 and not type check the function, you could use `CallableInstance<any, any>`.

**Comment by CL-Jeremy** [comment]
> Strange that the VS code linter can't handle it. Is it possible that restarting the program fixes that issue? I know my linter doesn't always pick up changes in dependent packages.

Unfortunately no. The linter is blazing fast. It could be considered as a bug then.
 
> The reason for the change is that the resulting function, with the version you've provided, is `(...args: any[]) => T`, whereas the version that I've now published is `(...args: A) => R`. That is to say, arguments are type checked. If you want to use version 2.0.0 and not type check the function, you could use `CallableInstance<any, any>`.

Yes, that's what I mean by seeing the analogy with Java's `<? extends T>`. Actually my function has exactly 4 numeric arguments and a Promise of void as return value, so that fits just well.

**Comment by CGamesPlay** [comment]
Closing this issue. I've tested with vite/4.0.3 and it works when importing:

```typescript
import CallableInstance from "callable-instance";
```

I believe this is the correct way of importing the module, however I'll not that this also worked for me when using esbuild.

```typescript
import * as CallableInstance from "callable-instance";
```
